export const TOOLTIPS: Record<string, string> = {
  sov: "Share of Voice — how much of the available search traffic in your niche your website captures.",
  da: "Domain Authority — a 0-100 score predicting how likely your site is to rank. Based on backlink quality. 40+ is solid for small businesses.",
  organic_traffic: "Estimated monthly visitors based on your keyword rankings and their search volumes. This is a model-based estimate, not actual analytics data. Real traffic (from Google Search Console) may differ significantly.",
  keywords: "Total search terms your site ranks for in Google's top 100 results.",
  mobile_speed: "Google PageSpeed score for mobile. Google ranks sites based on mobile performance. 90+ great, 50-89 needs work, below 50 poor.",
  position: "Your position in Google results. Position 1 = first result. Top 3 gets ~60% of clicks.",
  intent: "Why people search. Informational = learning. Commercial = comparing. Transactional = ready to buy.",
  cpc: "Cost Per Click — what advertisers pay for this keyword in Google Ads. Higher = more commercially valuable.",
  content_gaps: "Keywords your competitors rank for that you don't have content about. Your biggest growth opportunities.",
  difficulty: "How hard to rank for this keyword. Easy = weeks. Medium = months. Hard = 6+ months of work.",
  ai_readiness: "How likely AI tools like ChatGPT and Google AI Overviews are to cite your content. Higher is better.",
  content_depth: "AI prefers comprehensive, detailed content that thoroughly covers a topic.",
  topical_authority: "How strongly your site is associated with its core topics. Many related articles = higher authority.",
  eeat: "Experience, Expertise, Authority, Trust — Google's quality guidelines that AI tools also use to pick sources.",
  structured_data: "Special code helping AI understand your content. FAQ and Article schema make it easier to be cited.",
  qa_format: "Content structured as questions and answers gets pulled into AI responses far more often.",
  entity_clarity: "How clearly your site defines who you are and what you cover. Clear about pages and bios help AI trust you.",
  ai_volume: "Estimated monthly queries to AI tools like ChatGPT and Gemini for this topic.",
  ai_trend: "Whether this keyword is being asked more or less to AI tools compared to 3 months ago.",
  cms: "Content Management System — the platform used to manage website content. WordPress powers ~43% of all sites.",
  cdn: "Content Delivery Network — servers worldwide that make your site load faster for visitors everywhere.",
  lcp: "Largest Contentful Paint — how fast main content loads. Under 2.5 seconds is good.",
  fid: "First Input Delay — how fast your site responds to clicks. Under 100ms is good.",
  cls: "Cumulative Layout Shift — if elements jump around while loading. Under 0.1 is good.",
  ttfb: "Time To First Byte — server response speed. Under 800ms OK, under 200ms great.",
  seo_score: "How well this page follows SEO best practices. 90+ great, 70-89 okay, below 70 needs work.",
  referring_domains: "Number of unique websites linking to you.",
  dofollow: "Links that pass ranking power. Higher percentage is better.",
  overlap: "How many of a competitor's keywords match yours. Higher = more direct competitor.",
  backlinks: "Links from other websites to yours — they act like votes of confidence for Google.",
  lighthouse: "Google Lighthouse tests speed, accessibility, and SEO quality. 0-100 scores, higher is better.",
  core_web_vitals: "Google's key page experience metrics. These directly affect your search rankings.",
  action_plan: "Our AI analyzed your site and created a prioritized to-do list. Click any card for step-by-step instructions.",
  // Keyword tables
  kd: "Keyword Difficulty — how hard it is to rank. Under 30 is easy, 30-60 medium, 60+ hard.",
  pos: "Your position in Google results. Position 1 = first result. Top 3 gets ~60% of clicks.",
  competitors: "How many of your detected competitors rank for this keyword.",
  opp_score: "Opportunity score combines volume, difficulty, and competitor coverage. Higher = easier win with more traffic.",
  keyword_opportunities: "Keywords your competitors rank for that you don't. Ranked by opportunity score — higher means easier win with more traffic.",
  page_mapping: "Shows which keywords each page ranks for and flags missed optimizations — like a page ranking for a keyword but not including it in the title or H1.",
  content_roadmap: "Based on your keyword gaps and competitor analysis, these are the top content pieces you should create to capture new search traffic.",
  // Pages and linking
  internal_links: "Pages that rank for related keywords but don't link to each other. Adding internal links between related pages strengthens both pages in Google.",
  // Technical audit
  image_audit: "Images affect page speed, accessibility, and search rankings. Missing alt text hurts accessibility and image search. Large images slow your site down.",
  alt_text: "Alt text describes images for screen readers and search engines. Missing alt text means Google can't understand your images.",
  oversized_images: "Images over 200KB slow your site. Compress them without visible quality loss to speed up page loads.",
  tech_stack: "We scan your site's HTML, headers, scripts, and cookies to identify every technology. We use this to give you platform-specific recommendations.",
  perf_issues: "We cross-reference your tech stack with page speed data to find platform-specific performance problems.",
  speed_gains: "The projected improvement if you fix all performance issues above, based on resource sizes and render-blocking analysis.",
  // Backlinks
  pa: "Page Authority — predicts how well a specific page will rank. 0-100 scale based on link profile quality.",
  spam_score: "Spam Score — predicts how likely a site is to be penalized by search engines. Under 5 is healthy, 6-10 moderate, 11+ high risk.",
};
